spring:
  application:
    name: metrics-consumer
  datasource:
    url: jdbc:postgresql://localhost:5435/monitoring_system
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: metrics-topic-events
      properties:
        spring.json.trusted.packages: com.example.dto.metric

springdoc:
  swagger-ui:
    url: /openapi.yaml

server:
  port: 8081