openapi: 3.0.3
info:
  title: "kafka-monitoring-system API"
  description: "metrics-producer API"
  version: 1.0.0
paths:
  /metrics:
    post:
      summary: "Отправить метрики в кафку"
      operationId: "sendMetrics"
      responses:
        "200":
          description: "OK"